default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: abet_iuh
  host: 103.124.94.204
  username: phamdat
  password: Datdat@123
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
production:
  <<: *default
  