default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: abet_iuh_development
  host: localhost
  username: datpt
  password: 123456
  socket: /var/run/mysqld/mysqld.sock
production:
  <<: *default
  database: vendor_portal_ror_production